connection:
  server: "irc.trex.fi"
  port: 6667
  use_ssl: false
#  password: "your_password"
bot:
  nickname: "martoc"
  channels: ["#psykoosi","#kartano","#projekti"]
  command_prefix: "!"
thread_pool_size: 4

telegram:
  chat_ids: [-1002751088027]  # List of numeric chat IDs to broadcast to
